function [effData] = readEffData(dataDir, tool)

%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Tanis Mar\Documents\MATLAB\data\actionEffect_17Jul\data.log
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2014/07/17 14:21:54
%tool = 'hoe';

%% Initialize variables.
fprintf('reading %s effect data \n',tool);
dirname = [dataDir,'\',tool];
folders = dir(dirname);


%% Format string for each line of text:
%   column3: double (%f) -> effect Displacement
%   column4: double (%f) -> effect Angle
%   column5: double (%f) -> effect Rotation
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*f%*f%f%f%f%[^\n\r]';
delimiter = {' ','(',')'};

for foldI =1:length(folders)
    if (length(folders(foldI).name)>3) && (strcmp(folders(foldI).name(1:3),'eff'))
        filename = [dirname,'\',folders(foldI).name ,'\data.log'];        

        %% Open the text file.
        fileID = fopen(filename,'r');

        %% Read columns of data according to format string.
        % This call is based on the structure of the file used to generate this
        % code. If an error occurs for a different file, try regenerating the code
        % from the Import Tool.
        dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true,  'ReturnOnError', false);

        %% Close the text file.
        fclose(fileID);
        
        %% Create output variables        
        effDisp = dataArray{1};
        effAngle = dataArray{2}; 
        effRot = dataArray{3}; 
        
        %% Create output variable
        effData(:,1) = dataArray{1}; % Effected displacement
        effData(:,2) = dataArray{2}; % Effected Angle
        effData(:,3) = dataArray{3}; % Effected Rotation
    end    
    
end
%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;