function [actData] = readActData(dataDir, tool)

%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Tanis Mar\Documents\MATLAB\data\actionEffect_17Jul\data.log
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2014/07/17 14:21:54
%tool = 'hoe';

%% Initialize variables.
fprintf('Reading %s action data \n',tool);
dirname = [dataDir,'\',tool];
folders = dir(dirname);


%% Format string for each line of text:
%   column3: double (%f) -> action angle
%   column4: double (%f) -> action displacement (fixed)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*f%*f%f%f%[^\n\r]';
delimiter = {' ','(',')'};

for foldI =1:length(folders)
    if (length(folders(foldI).name)>3) && (strcmp(folders(foldI).name(1:3),'act'))
        filename = [dirname,'\',folders(foldI).name ,'\data.log'];     

        %% Open the text file.
        fileID = fopen(filename,'r');

        %% Read columns of data according to format string.
        % This call is based on the structure of the file used to generate this
        % code. If an error occurs for a different file, try regenerating the code
        % from the Import Tool.
        dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true,  'ReturnOnError', false);

        %% Close the text file.
        fclose(fileID);
        
        %% Create output variable
        actData(:,1) = dataArray{1}; % Action Angle
        actData(:,2) = dataArray{2}; % Action Displacement (fixed)

    end    
    
end
%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;