function [toolFeatures,stdNorm,meanNorm] = readFeatures(dataDir, tool, normFlag)

if (nargin<3 ||isempty(normFlag))
    normFlag = 0;
end

%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/icub/tanis/toolFeats/affLearn/data.log
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2014/07/07 11:54:05

%% Initialize variables.
toolFeaturesRaw = [];
fprintf('reading %s features',tool);
dirname = [dataDir,'\',tool];
folders = dir(dirname);

for foldI =1:length(folders)
    if (length(folders(foldI).name)>3) && (strcmp(folders(foldI).name(1:7),'featExt'))
        filename = [dirname,'\',folders(foldI).name, '\data.log']
        delimiter = ' ';

        %% Format string for each line of text:
        % For more information, see the TEXTSCAN documentation.
        formatSpec = '%*s%*s%*s%*s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%*s%[^\n\r]';
        
        %% Open the text file.
        fileID = fopen(filename,'r');

        %% Read columns of data according to format string.
        % This call is based on the structure of the file used to generate this
        % code. If an error occurs for a different file, try regenerating the code
        % from the Import Tool.
        dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true,  'ReturnOnError', false);

        %% Close the text file.
        fclose(fileID);

        %% Post processing for unimportable data.
        % No unimportable data rules were applied during the import, so no post
        % processing code is included. To generate code which works for
        % unimportable data, select unimportable cells in a file and regenerate the
        % script.

        %% Create output variable
        dataRaw = [dataArray{1:end-1}];
        %% Clear temporary variables
        clearvars filename delimiter formatSpec fileID dataArray ans;
        toolFeaturesRaw = [toolFeaturesRaw; dataRaw];
    end
end
if (normFlag)
    [toolFeatures,stdNorm,meanNorm] = normalizeData(toolFeaturesRaw);
else 
    toolFeatures = toolFeaturesRaw;
    stdNorm = 1;
    meanNorm = 0;
end
